version: '3.8'

services:
  db:
    image: mongo:${MONGO_VERSION}
    container_name: db
    networks:
      - net_A
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  server:
    image: jagna/server-api:latest
    container_name: server
    depends_on:
      - db
    networks:
      - net_A
    ports:
      - "3003:3000"

networks:
  net_A:

volumes:
  mongo_data:
