version: '3'

services:
  web:
    image: nginx:latest
    container_name: web
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - my_network
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: my_database
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

